---
# tasks file for memcached
- name: start memcached
  k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: "{{ meta.name }}-memcached"
        namespace: "{{ meta.namespace }}"
      spec:
        replicas: "{{size}}"
        selector:
          matchLabels:
            app: memcached
        template:
          metadata:
            labels:
              app: memcached
          spec:
            containers:
              - name: memcached
                command:
                  - memcached
                  - -m=64
                  - -o
                  - modern
                  - -v
                image: "docker.io/memcached:1.4.36-alpine"
                ports:
                  - containerPort: 11211

- name: create memcached kind Service
  k8s:
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: "{{ meta.name }}-memcached"
        namespace: "{{ meta.namespace }}"
      spec:
        selector:
          app: memcached
        type: ClusterIP
        ports:
          - name: memcached
            port: 11211
            targetPort: 11211
